name: Selenium CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cache Maven dependencies (faster builds)
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      # 4. Install Chrome
      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      # 5. Run tests
      - name: Run Selenium Tests
        run: mvn clean test

      # 6. Generate Allure report
      - name: Generate Allure Report
        run: |
          mvn io.qameta.allure:allure-maven:report

      # 7. Upload Allure results
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      # 8git YrY Upload Allure report (HTML)
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin